import { DroneComponent, ConfiguratorStep } from './types';

export const CONFIGURATOR_STEPS: ConfiguratorStep[] = [
  {
    id: 'frame',
    label: 'Frame',
    componentType: 'frame',
    description: 'Escolha o chassi do seu drone. O tamanho define a categoria e o desempenho.',
    required: true,
  },
  {
    id: 'motor',
    label: 'Motores',
    componentType: 'motor',
    description: 'Os motores definem a potência, velocidade e eficiência do drone.',
    required: true,
  },
  {
    id: 'esc',
    label: 'ESC',
    componentType: 'esc',
    description: 'O controlador de velocidade eletrônico gerencia a potência enviada aos motores.',
    required: true,
  },
  {
    id: 'flight-controller',
    label: 'Controladora de Voo',
    componentType: 'flight-controller',
    description: 'O cérebro do drone. Processa sensores e controla a estabilidade.',
    required: true,
  },
  {
    id: 'propeller',
    label: 'Hélices',
    componentType: 'propeller',
    description: 'As hélices determinam a sustentação e eficiência aerodinâmica.',
    required: true,
  },
  {
    id: 'battery',
    label: 'Bateria',
    componentType: 'battery',
    description: 'A bateria define a autonomia e o peso total do drone.',
    required: true,
  },
  {
    id: 'camera',
    label: 'Câmera',
    componentType: 'camera',
    description: 'Escolha a câmera conforme o uso: FPV, filmagem ou ambos.',
    required: false,
  },
  {
    id: 'vtx',
    label: 'VTX',
    componentType: 'vtx',
    description: 'O transmissor de vídeo envia a imagem da câmera para seus óculos ou monitor.',
    required: false,
  },
  {
    id: 'receiver',
    label: 'Receptor',
    componentType: 'receiver',
    description: 'Recebe os comandos do controle remoto.',
    required: true,
  },
  {
    id: 'radio',
    label: 'Rádio / Controle',
    componentType: 'radio',
    description: 'O controle remoto que você usará para pilotar.',
    required: false,
  },
  {
    id: 'summary',
    label: 'Resumo',
    componentType: 'summary',
    description: 'Revise sua configuração e solicite o orçamento.',
    required: false,
  },
];

export const DRONE_COMPONENTS: DroneComponent[] = [
  // FRAMES
  {
    id: 'frame-beginner-5inch',
    name: 'Frame 5" Iniciante',
    brand: 'Generic',
    type: 'frame',
    price: 89.9,
    weight: 85,
    description: 'Frame robusto ideal para iniciantes. Fácil de reparar e montar.',
    specs: { tamanho: '5"', material: 'Nylon reforçado', wheelbase: '220mm' },
    compatibleCategories: ['iniciante'],
    inStock: true,
  },
  {
    id: 'frame-fpv-5inch',
    name: 'iFlight Nazgul5 V3',
    brand: 'iFlight',
    type: 'frame',
    price: 219.9,
    weight: 120,
    description: 'Frame 5" de alta performance para FPV freestyle e corrida.',
    specs: { tamanho: '5"', material: 'Fibra de carbono 3K', wheelbase: '227mm' },
    compatibleCategories: ['fpv', 'freestyle'],
    inStock: true,
  },
  {
    id: 'frame-freestyle-5inch',
    name: 'Armattan Marmotte 5"',
    brand: 'Armattan',
    type: 'frame',
    price: 389.0,
    weight: 98,
    description: 'Frame lifetime warranty para freestyle. Leve e resistente.',
    specs: { tamanho: '5"', material: 'Fibra de carbono 4K', wheelbase: '225mm' },
    compatibleCategories: ['freestyle', 'fpv'],
    inStock: true,
  },
  {
    id: 'frame-cinema-7inch',
    name: 'TBS Source One V5 7"',
    brand: 'TBS',
    type: 'frame',
    price: 159.9,
    weight: 110,
    description: 'Frame 7" para filmagem e long range. Estável e versátil.',
    specs: { tamanho: '7"', material: 'Fibra de carbono', wheelbase: '295mm' },
    compatibleCategories: ['filmagem', 'long-range'],
    inStock: true,
  },
  {
    id: 'frame-longrange-7inch',
    name: 'Diatone Roma F7',
    brand: 'Diatone',
    type: 'frame',
    price: 249.9,
    weight: 130,
    description: 'Frame 7" especializado para voos de longo alcance.',
    specs: { tamanho: '7"', material: 'Fibra de carbono', wheelbase: '300mm' },
    compatibleCategories: ['long-range', 'filmagem'],
    inStock: false,
  },

  // MOTORS
  {
    id: 'motor-beginner-2306',
    name: 'BrotherHobby Tornado T2',
    brand: 'BrotherHobby',
    type: 'motor',
    price: 159.6,
    weight: 120,
    description: 'Conjunto 4x motores 2306 2450KV. Custo-benefício para iniciantes.',
    specs: { tamanho: '2306', kv: '2450KV', tensão: '3-4S', quantidade: '4x' },
    compatibleCategories: ['iniciante', 'fpv'],
    inStock: true,
  },
  {
    id: 'motor-fpv-2306',
    name: 'T-Motor F40 Pro IV',
    brand: 'T-Motor',
    type: 'motor',
    price: 399.6,
    weight: 116,
    description: 'Conjunto 4x motores premium para FPV racing e freestyle.',
    specs: { tamanho: '2306', kv: '2400KV', tensão: '4-6S', quantidade: '4x' },
    compatibleCategories: ['fpv', 'freestyle'],
    inStock: true,
  },
  {
    id: 'motor-freestyle-2207',
    name: 'EMAX Eco II 2207',
    brand: 'EMAX',
    type: 'motor',
    price: 239.6,
    weight: 140,
    description: 'Conjunto 4x motores 2207 para freestyle. Potência e suavidade.',
    specs: { tamanho: '2207', kv: '2400KV', tensão: '4-6S', quantidade: '4x' },
    compatibleCategories: ['freestyle', 'fpv'],
    inStock: true,
  },
  {
    id: 'motor-cinema-2806',
    name: 'T-Motor Air Gear 350',
    brand: 'T-Motor',
    type: 'motor',
    price: 459.6,
    weight: 180,
    description: 'Conjunto 4x motores para filmagem. Alta eficiência e baixa vibração.',
    specs: { tamanho: '2806', kv: '1150KV', tensão: '4S', quantidade: '4x' },
    compatibleCategories: ['filmagem', 'long-range'],
    inStock: true,
  },
  {
    id: 'motor-longrange-3115',
    name: 'T-Motor MN3110',
    brand: 'T-Motor',
    type: 'motor',
    price: 599.6,
    weight: 220,
    description: 'Conjunto 4x motores para long range. Máxima eficiência.',
    specs: { tamanho: '3115', kv: '700KV', tensão: '4-6S', quantidade: '4x' },
    compatibleCategories: ['long-range'],
    inStock: false,
  },

  // ESCs
  {
    id: 'esc-beginner-30a',
    name: 'Flycolor Raptor 30A 4-em-1',
    brand: 'Flycolor',
    type: 'esc',
    price: 159.9,
    weight: 18,
    description: 'ESC 4-em-1 30A para iniciantes. Fácil instalação e confiável.',
    specs: { corrente: '30A', tensão: '3-4S', protocolo: 'DSHOT600', formato: '4-em-1' },
    compatibleCategories: ['iniciante', 'fpv'],
    inStock: true,
  },
  {
    id: 'esc-fpv-45a',
    name: 'Hobbywing XRotor 45A 4-em-1',
    brand: 'Hobbywing',
    type: 'esc',
    price: 289.9,
    weight: 24,
    description: 'ESC 4-em-1 45A para racing e freestyle. Alta performance.',
    specs: { corrente: '45A', tensão: '4-6S', protocolo: 'DSHOT1200', formato: '4-em-1' },
    compatibleCategories: ['fpv', 'freestyle'],
    inStock: true,
  },
  {
    id: 'esc-freestyle-50a',
    name: 'T-Motor F55A Pro II 4-em-1',
    brand: 'T-Motor',
    type: 'esc',
    price: 389.9,
    weight: 26,
    description: 'ESC 4-em-1 55A para freestyle exigente. Suporta picos altos.',
    specs: { corrente: '55A', tensão: '4-6S', protocolo: 'DSHOT1200', formato: '4-em-1' },
    compatibleCategories: ['freestyle', 'fpv'],
    inStock: true,
  },
  {
    id: 'esc-cinema-40a',
    name: 'Hobbywing XRotor 40A 4-em-1',
    brand: 'Hobbywing',
    type: 'esc',
    price: 349.9,
    weight: 22,
    description: 'ESC suave e confiável para filmagem e long range.',
    specs: { corrente: '40A', tensão: '4-6S', protocolo: 'DSHOT600', formato: '4-em-1' },
    compatibleCategories: ['filmagem', 'long-range'],
    inStock: true,
  },

  // FLIGHT CONTROLLERS
  {
    id: 'fc-beginner-f405',
    name: 'Matek F405-Wing',
    brand: 'Matek',
    type: 'flight-controller',
    price: 249.9,
    weight: 12,
    description: 'Controladora robusta para iniciantes. Betaflight integrado.',
    specs: { processador: 'F405', giroscópio: 'ICM42688', barômetro: 'Sim', bec: '5V/2A' },
    compatibleCategories: ['iniciante', 'fpv'],
    inStock: true,
  },
  {
    id: 'fc-fpv-f7',
    name: 'Speedybee F7 V3',
    brand: 'Speedybee',
    type: 'flight-controller',
    price: 319.9,
    weight: 10,
    description: 'Controladora F7 de alta performance para FPV racing.',
    specs: { processador: 'F7', giroscópio: 'ICM42688-P', barômetro: 'BMP280', bec: '9V/3A' },
    compatibleCategories: ['fpv', 'freestyle', 'iniciante'],
    inStock: true,
  },
  {
    id: 'fc-freestyle-f7',
    name: 'Holybro Kakute H7 V2',
    brand: 'Holybro',
    type: 'flight-controller',
    price: 429.9,
    weight: 11,
    description: 'Controladora premium para freestyle e racing exigente.',
    specs: { processador: 'H7', giroscópio: 'ICM42688-P', barômetro: 'MS5611', bec: '5V/3A' },
    compatibleCategories: ['freestyle', 'fpv'],
    inStock: true,
  },
  {
    id: 'fc-cinema-f7',
    name: 'Matek H743-Slim V3',
    brand: 'Matek',
    type: 'flight-controller',
    price: 489.9,
    weight: 15,
    description: 'Controladora para filmagem com GPS e ArduPilot.',
    specs: { processador: 'H743', giroscópio: 'ICM42688', gps: 'Sim', bec: '5V/3A' },
    compatibleCategories: ['filmagem', 'long-range'],
    inStock: true,
  },

  // PROPELLERS
  {
    id: 'prop-beginner-5045',
    name: 'HQProp 5045 Iniciante (4x)',
    brand: 'HQProp',
    type: 'propeller',
    price: 39.9,
    weight: 24,
    description: 'Hélices 5" resistentes e acessíveis para iniciantes.',
    specs: { tamanho: '5"', passo: '4.5"', pás: '3', material: 'Policarbonato' },
    compatibleCategories: ['iniciante'],
    inStock: true,
  },
  {
    id: 'prop-fpv-5152',
    name: 'HQProp 5.1X5.2X3 V1S (4x)',
    brand: 'HQProp',
    type: 'propeller',
    price: 59.9,
    weight: 20,
    description: 'Hélices performáticas para FPV racing e freestyle.',
    specs: { tamanho: '5"', passo: '5.2"', pás: '3', material: 'Policarbonato reforçado' },
    compatibleCategories: ['fpv', 'freestyle'],
    inStock: true,
  },
  {
    id: 'prop-cinema-7045',
    name: 'T-Motor 7045 Eficiência (4x)',
    brand: 'T-Motor',
    type: 'propeller',
    price: 89.9,
    weight: 32,
    description: 'Hélices 7" para máxima eficiência e tempo de voo.',
    specs: { tamanho: '7"', passo: '4.5"', pás: '2', material: 'Fibra de carbono' },
    compatibleCategories: ['filmagem', 'long-range'],
    inStock: true,
  },

  // BATTERIES
  {
    id: 'bat-4s-1500',
    name: 'Tattu 4S 1500mAh 75C',
    brand: 'Tattu',
    type: 'battery',
    price: 169.9,
    weight: 145,
    description: 'Bateria 4S ideal para iniciantes e FPV. Boa autonomia.',
    specs: { células: '4S', capacidade: '1500mAh', descarga: '75C', conector: 'XT60' },
    compatibleCategories: ['iniciante', 'fpv'],
    inStock: true,
  },
  {
    id: 'bat-4s-1800',
    name: 'Tattu 4S 1800mAh 95C',
    brand: 'Tattu',
    type: 'battery',
    price: 209.9,
    weight: 185,
    description: 'Bateria 4S para freestyle. Mais capacidade para voos mais longos.',
    specs: { células: '4S', capacidade: '1800mAh', descarga: '95C', conector: 'XT60' },
    compatibleCategories: ['fpv', 'freestyle', 'iniciante'],
    inStock: true,
  },
  {
    id: 'bat-6s-2200',
    name: 'CNHL Black Series 6S 2200mAh',
    brand: 'CNHL',
    type: 'battery',
    price: 299.9,
    weight: 290,
    description: 'Bateria 6S para freestyle exigente e alta performance.',
    specs: { células: '6S', capacidade: '2200mAh', descarga: '100C', conector: 'XT60' },
    compatibleCategories: ['freestyle', 'fpv'],
    inStock: true,
  },
  {
    id: 'bat-4s-3000',
    name: 'Tattu R-Line 4S 3000mAh',
    brand: 'Tattu',
    type: 'battery',
    price: 349.9,
    weight: 320,
    description: 'Bateria 4S de alta capacidade para filmagem e long range.',
    specs: { células: '4S', capacidade: '3000mAh', descarga: '30C', conector: 'XT60' },
    compatibleCategories: ['filmagem', 'long-range'],
    inStock: true,
  },

  // CAMERAS
  {
    id: 'cam-fpv-caddx',
    name: 'Caddx Ratel 2 FPV',
    brand: 'Caddx',
    type: 'camera',
    price: 119.9,
    weight: 18,
    description: 'Câmera analógica FPV de alta qualidade. Baixa latência.',
    specs: { resolução: '1200TVL', sensor: 'STARVIS', wdr: 'Sim', formato: '1/1.8"' },
    compatibleCategories: ['fpv', 'freestyle', 'iniciante'],
    inStock: true,
  },
  {
    id: 'cam-cinema-gopro',
    name: 'GoPro Hero 12 Black',
    brand: 'GoPro',
    type: 'camera',
    price: 1999.9,
    weight: 153,
    description: 'A melhor câmera de ação para filmagens profissionais de drone.',
    specs: { resolução: '5.3K/60fps', estabilização: 'HyperSmooth 6.0', bateria: 'Interna' },
    compatibleCategories: ['filmagem'],
    inStock: true,
  },
  {
    id: 'cam-fpv-digital',
    name: 'DJI O3 Air Unit',
    brand: 'DJI',
    type: 'camera',
    price: 1299.9,
    weight: 35,
    description: 'Sistema FPV digital DJI. Imagem nítida e longa distância.',
    specs: { resolução: '4K/60fps', latência: '<20ms', alcance: '10km', gravação: 'Interna' },
    compatibleCategories: ['fpv', 'freestyle', 'filmagem'],
    inStock: true,
  },

  // VTX
  {
    id: 'vtx-analog-500mw',
    name: 'TBS Unify Pro32 HV',
    brand: 'TBS',
    type: 'vtx',
    price: 159.9,
    weight: 6,
    description: 'VTX analógico 500mW de alta qualidade para FPV.',
    specs: { potência: '500mW', canais: '40ch', protocolo: 'SmartAudio', tensão: '7-24V' },
    compatibleCategories: ['fpv', 'freestyle', 'iniciante'],
    inStock: true,
  },
  {
    id: 'vtx-digital-dji',
    name: 'DJI O3 Air Unit (integrado)',
    brand: 'DJI',
    type: 'vtx',
    price: 0,
    weight: 0,
    description: 'VTX integrado no DJI O3 Air Unit. Não é necessário VTX separado.',
    specs: { potência: 'Integrado', sistema: 'DJI Digital', alcance: '10km' },
    compatibleCategories: ['fpv', 'freestyle', 'filmagem'],
    inStock: true,
  },

  // RECEIVERS
  {
    id: 'rx-elrs-24g',
    name: 'ELRS EP1 Lite 2.4GHz',
    brand: 'BETAFPV',
    type: 'receiver',
    price: 89.9,
    weight: 2,
    description: 'Receptor ExpressLRS 2.4GHz. Baixa latência e longo alcance.',
    specs: { protocolo: 'ExpressLRS', frequência: '2.4GHz', latência: '≤1ms', alcance: '5km' },
    compatibleCategories: ['fpv', 'freestyle', 'iniciante', 'filmagem', 'long-range'],
    inStock: true,
  },
  {
    id: 'rx-elrs-900mhz',
    name: 'ELRS ER9X 900MHz',
    brand: 'BETAFPV',
    type: 'receiver',
    price: 119.9,
    weight: 3,
    description: 'Receptor ELRS 900MHz para máximo alcance. Ideal para long range.',
    specs: { protocolo: 'ExpressLRS', frequência: '900MHz', latência: '≤2ms', alcance: '20km+' },
    compatibleCategories: ['long-range', 'filmagem'],
    inStock: true,
  },

  // RADIOS
  {
    id: 'radio-radiomaster-boxer',
    name: 'RadioMaster Boxer',
    brand: 'RadioMaster',
    type: 'radio',
    price: 699.9,
    weight: 530,
    description: 'Rádio compacto com ELRS integrado. Excelente custo-benefício.',
    specs: { protocolo: 'ELRS/Multi', canais: '16ch', display: 'Colorido', bateria: 'Li-ion 18650' },
    compatibleCategories: ['fpv', 'freestyle', 'iniciante', 'filmagem', 'long-range'],
    inStock: true,
  },
  {
    id: 'radio-radiomaster-tx16s',
    name: 'RadioMaster TX16S Mark II',
    brand: 'RadioMaster',
    type: 'radio',
    price: 1199.9,
    weight: 680,
    description: 'Rádio premium para pilotos exigentes. Máximo de funcionalidades.',
    specs: { protocolo: 'ELRS/Multi', canais: '16ch', display: 'Touch colorido', bateria: '2x 18650' },
    compatibleCategories: ['fpv', 'freestyle', 'filmagem', 'long-range'],
    inStock: true,
  },
];

export const ASSEMBLY_PRICE = 149.9;

export const DRONE_CATEGORIES = [
  {
    id: 'iniciante' as const,
    name: 'Iniciante',
    description: 'Perfeito para quem está começando. Fácil de voar, robusto e acessível.',
    image: '/images/iniciante.jpg',
    icon: '🚀',
    color: 'from-green-500 to-teal-500',
    features: ['Fácil de aprender', 'Resistente a quedas', 'Acessível', 'Suporte dedicado'],
    priceRange: 'R$ 800 – R$ 1.500',
  },
  {
    id: 'fpv' as const,
    name: 'FPV Racing',
    description: 'Alta velocidade e adrenalina. Para quem quer sentir cada curva em primeira pessoa.',
    image: '/images/fpv.jpg',
    icon: '⚡',
    color: 'from-yellow-500 to-orange-500',
    features: ['Alta velocidade', 'Baixa latência', 'Configurável', 'Competitivo'],
    priceRange: 'R$ 1.500 – R$ 3.000',
  },
  {
    id: 'freestyle' as const,
    name: 'Freestyle',
    description: 'Acrobacias e manobras impressionantes. Para quem quer ser criativo nos céus.',
    image: '/images/freestyle.jpg',
    icon: '🎯',
    color: 'from-purple-500 to-pink-500',
    features: ['Ágil e responsivo', 'Manobras acrobáticas', 'Alta potência', 'Durável'],
    priceRange: 'R$ 1.800 – R$ 3.500',
  },
  {
    id: 'filmagem' as const,
    name: 'Filmagem',
    description: 'Estável, suave e com qualidade cinematográfica. Para capturar momentos únicos.',
    image: '/images/filmagem.jpg',
    icon: '🎬',
    color: 'from-blue-500 to-cyan-500',
    features: ['Estabilidade cinematográfica', 'Alta qualidade de imagem', 'Gimbal', 'GPS'],
    priceRange: 'R$ 2.500 – R$ 6.000',
  },
  {
    id: 'long-range' as const,
    name: 'Long Range',
    description: 'Autonomia máxima para explorar locais distantes com segurança e controle.',
    image: '/images/longrange.jpg',
    icon: '🌐',
    color: 'from-red-500 to-rose-500',
    features: ['Longo alcance', 'Alta autonomia', 'GPS avançado', 'Retorno automático'],
    priceRange: 'R$ 2.000 – R$ 5.000',
  },
];
